version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root123
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: postgress
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${PORT:-3000}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db